-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgm1Jbr2ctPBnbFkd4
3TRhjAX5icMEACOYvSMhhWO5gnugCgYIKoZIzj0DAQehRANCAAShWYpjDbxVuoMY
9hd8NRYmRjP3ET5+EFyixuBoRQ1EzyJHhLiQkRel2MZMVnev0jYjPlwx4urbSCuF
U8gKNAIO
-----END PRIVATE KEY-----